spring:
  datasource:
    username: ${DB_HELLO_USER}
    password: ${DB_HELLO_PASS}
    url: ${DB_HELLO_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Aplicacao piloto Hello

server:
  port: 8080